{{- if .Values.influxdb.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "influxdb-tsdb.fullname" . }}
  labels:
    {{- include "influxdb-tsdb.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.influxdb.persistence.storageClass }}
  resources:
    requests:
      storage: {{ .Values.influxdb.persistence.size }}
{{- end }}
