apiVersion: v1
kind: Secret
metadata:
  name: {{ include "influxdb-tsdb.fullname" . }}
  labels:
    {{- include "influxdb-tsdb.labels" . | nindent 4 }}
type: Opaque
data:
  admin-password: {{ .Values.influxdb.adminUser.password | b64enc | quote }}
  admin-token: {{ .Values.influxdb.token.value | b64enc | quote }}
